import { notFound } from "next/navigation";
import { ModuleScreen, type ModuleDefinition } from "@/components/module-screen";

const metric = (label: string, value = "—", detail = "Available when this module is activated") => ({ label, value, detail });
const capability = (name: string, description: string, state: "Available" | "Planned" | "Needs setup" = "Planned") => ({ name, description, state });

const definitions: Record<string, ModuleDefinition> = {
  overview: { eyebrow: "Platform", title: "Platform overview", description: "Monitor customer growth, onboarding readiness, integrations, processing, and overall platform health.", status: "partial", primaryAction: "Open customer accounts", primaryHref: "/admin", metrics: [metric("Active customers", "1", "Tenant workspaces in service"), metric("Need onboarding", "0", "No blocked customers"), metric("Connected integrations", "0", "Manual mode is active"), metric("Platform status", "Healthy", "API and web available")], capabilities: [capability("Customer operations", "Create, suspend, reactivate, and enter audited support sessions.", "Available"), capability("Onboarding visibility", "Track customer readiness and connection mode.", "Available"), capability("Operational alerts", "Webhook, queue, and messaging failure summaries.", "Planned")] },
  onboarding: { eyebrow: "Platform", title: "Onboarding queue", description: "Prioritize customer workspaces that need business, location, consent, template, or POS assistance.", status: "partial", primaryAction: "Open customer accounts", primaryHref: "/admin", metrics: [metric("Not started", "0", "No workspaces waiting"), metric("In progress", "0", "No active onboarding"), metric("Ready for POS", "1", "AL Barber Shop"), metric("Completed", "1", "All essentials complete")], capabilities: [capability("Readiness calculation", "Server-derived checklist covers core onboarding requirements.", "Available"), capability("Audited concierge setup", "One-hour tenant-specific support sessions.", "Available"), capability("Assignment and due dates", "Route onboarding cases to platform managers.", "Planned")] },
  managers: { eyebrow: "Platform", title: "Platform managers", description: "Control staff access, business assignments, and support permissions across the platform.", metrics: [metric("Super admins", "1"), metric("Platform managers", "0"), metric("Assigned customers", "0"), metric("Pending invites", "0")], capabilities: [capability("Platform roles", "Super-admin and platform-manager roles exist and are enforced.", "Available"), capability("Business assignments", "Limit managers to assigned customer workspaces."), capability("Staff invitations", "Secure invitation and account activation flow.")] },
  integrations: { eyebrow: "Operations", title: "Integration health", description: "See POS connectivity, credential state, provider health, and customer setup status across all tenants.", status: "partial", metrics: [metric("Connected", "0", "No external POS connected"), metric("Setup required", "0", "No blocked connection"), metric("Manual mode", "1", "AL Barber Shop"), metric("Errors", "0", "No integration errors")], capabilities: [capability("Generic API credentials", "Hashed bearer keys and encrypted HMAC secrets.", "Available"), capability("Connection inventory", "Tenant-scoped POS connection status records.", "Available"), capability("Square OAuth health", "Token, scope, merchant, and location health.", "Needs setup")] },
  messages: { eyebrow: "Operations", title: "Messaging activity", description: "Platform-wide delivery, failure, reply, opt-out, and usage visibility without exposing unnecessary PII.", metrics: [metric("Sent today"), metric("Delivered"), metric("Failed"), metric("Opt-outs")], capabilities: [capability("Provider delivery overview", "Aggregate Twilio status callbacks and error groups."), capability("Tenant usage", "Monitor plan allowances and abnormal sending patterns."), capability("Compliance events", "Surface opt-outs and suppression health without raw message PII.")] },
  webhooks: { eyebrow: "Operations", title: "Webhook events", description: "Inspect verified provider events, durable processing state, duplicate detection, and retry history.", status: "partial", metrics: [metric("Received today", "0"), metric("Processed", "0"), metric("Failed", "0"), metric("Duplicates", "0")], capabilities: [capability("Generic signature verification", "Raw-body HMAC validation and replay tolerance.", "Available"), capability("Durable event viewer", "Search event metadata and processing results."), capability("Permission-checked reprocessing", "Retry through the same idempotent handler.")] },
  jobs: { eyebrow: "Operations", title: "Failed processing", description: "Review queue failures across webhooks, integrations, messaging, media, and analytics.", metrics: [metric("Open failures", "0"), metric("Retried today", "0"), metric("Dead letter", "0"), metric("Oldest failure", "—")], capabilities: [capability("Queue inventory", "Separate operational queues are configured.", "Available"), capability("Failure details", "Sanitized exception, request ID, queue, and attempts."), capability("Safe retry", "Permission-checked retry for idempotent jobs.")] },
  audit: { eyebrow: "Operations", title: "Audit log", description: "Search sensitive platform and customer changes by actor, tenant, action, target, and request ID.", status: "partial", metrics: [metric("Events today", "—", "Audit persistence active"), metric("Support sessions", "—"), metric("Platform changes", "—"), metric("Exports", "0")], capabilities: [capability("Audit persistence", "Actor, tenant, target, changed fields, and request ID.", "Available"), capability("Support-session records", "Reason and administrator identity are retained.", "Available"), capability("Search and export", "Operational filters and protected CSV export.")] },
  analytics: { eyebrow: "Insights", title: "Platform analytics", description: "Understand customer adoption, message performance, link activity, opt-outs, and automation outcomes.", metrics: [metric("Active workspaces", "1"), metric("Messages this month"), metric("Link click rate"), metric("Automation skips")], capabilities: [capability("Workspace growth", "Signup, activation, onboarding, and churn cohorts."), capability("Messaging performance", "Delivery and failure metrics without false review attribution."), capability("Operational exports", "Aggregate reports with tenant and date filters.")] },
  billing: { eyebrow: "Insights", title: "Plans & billing", description: "Manage subscription plans, usage entitlements, invoices, and customer billing health.", metrics: [metric("Monthly revenue"), metric("Active subscriptions"), metric("Trials", "1"), metric("Past due", "0")], capabilities: [capability("Plan catalogue", "Feature and usage entitlements."), capability("Subscription lifecycle", "Trial, active, past-due, cancelled, and grace periods."), capability("Invoice visibility", "Hosted payment and downloadable invoices.")] },
  health: { eyebrow: "Insights", title: "System health", description: "Monitor the API, database, cache, queues, storage, and external provider dependencies.", status: "partial", metrics: [metric("API", "Healthy", "Liveness endpoint available"), metric("Database", "Healthy", "Readiness check available"), metric("Queues", "Local", "Worker must be running"), metric("Providers", "Not configured", "Twilio and Square pending")], capabilities: [capability("Liveness endpoint", "Fast process health endpoint.", "Available"), capability("Dependency readiness", "Database and Redis readiness checks.", "Available"), capability("Alerting and history", "Availability history and incident notifications.")] },
  settings: { eyebrow: "Configuration", title: "Platform settings", description: "Configure platform identity, environment policies, default limits, retention, and support behavior.", metrics: [metric("Environment", "Local"), metric("Default region", "US"), metric("Retention policy", "Draft"), metric("Feature flags", "0")], capabilities: [capability("Brand and sender defaults", "Platform-wide identity and operational email settings."), capability("Retention policy", "Webhook, media, audit, and tracking retention defaults."), capability("Feature controls", "Safe staged rollout by environment and tenant.")] },
  help: { eyebrow: "Configuration", title: "Help & documentation", description: "Access product, integration, security, deployment, and operational runbooks.", status: "partial", primaryAction: "Open customer accounts", primaryHref: "/admin", metrics: [metric("Product guides", "10"), metric("Integration guides", "2"), metric("Runbooks", "2"), metric("Open incidents", "0")], capabilities: [capability("Architecture and security", "Repository documentation covers core decisions.", "Available"), capability("Integration guides", "Generic and Square integration documentation.", "Available"), capability("Support case management", "Internal support requests and resolution history.")] },
};

export default async function AdminModulePage({ params }: { params: Promise<{ module: string }> }) {
  const { module } = await params;
  const definition = definitions[module];
  if (!definition) notFound();
  return <ModuleScreen module={definition}/>;
}
