"use client";

import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";

type Customer = { id: string; first_name: string; last_name?: string };
type Location = { id: string; name: string };
type Delivery = { id: string; status: string; channel: string; body_snapshot?: string; template?: { name: string }; review_link?: { click_count: number; first_clicked_at?: string } };
type Visit = { id: string; source: string; type: string; status: string; completed_at: string; customer?: Customer; location: Location; dispatches: { id: string; decision: string; reason_code?: string; scheduled_for?: string; rule?: { name: string }; delivery?: Delivery }[] };

export default function VisitsPage() {
  const [visits, setVisits] = useState<Visit[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [selected, setSelected] = useState<Visit | null>(null); const [manualOpen, setManualOpen] = useState(false); const [message, setMessage] = useState(""); const [search, setSearch] = useState("");
  async function load() { const [visitResult, businessResult, customerResult] = await Promise.all([api<{ data: Visit[] }>("/api/v1/visits", {}, true), api<{ data: { locations: Location[] } }>("/api/v1/business", {}, true), api<{ data: Customer[] }>("/api/v1/customers", {}, true)]); setVisits(visitResult.data); setLocations(businessResult.data.locations); setCustomers(customerResult.data); }
  useEffect(() => { void Promise.all([api<{ data: Visit[] }>("/api/v1/visits", {}, true), api<{ data: { locations: Location[] } }>("/api/v1/business", {}, true), api<{ data: Customer[] }>("/api/v1/customers", {}, true)]).then(([visitResult, businessResult, customerResult]) => { setVisits(visitResult.data); setLocations(businessResult.data.locations); setCustomers(customerResult.data); }).catch((error: Error) => setMessage(error.message)); }, []);
  const filtered = useMemo(() => visits.filter((visit) => `${visit.customer?.first_name ?? ""} ${visit.customer?.last_name ?? ""} ${visit.location.name} ${visit.source}`.toLowerCase().includes(search.toLowerCase())), [visits, search]);
  const sent = visits.flatMap((visit) => visit.dispatches).filter((item) => item.delivery).length; const clicked = visits.flatMap((visit) => visit.dispatches).filter((item) => item.delivery?.review_link?.first_clicked_at).length;
  async function createVisit(data: FormData) { try { await api("/api/v1/visits", { method: "POST", body: JSON.stringify({ location_id: data.get("location_id"), customer_id: data.get("customer_id"), completed_at: new Date(String(data.get("completed_at"))).toISOString(), type: data.get("type"), amount: data.get("amount") || null, currency: data.get("currency") || null, consent_source: data.get("consent_source") || null }) }, true); setManualOpen(false); setMessage("Manual visit recorded and matching automations evaluated."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to record visit."); } }
  return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Customer activity</p><h1 className="page-title">Visits</h1><p className="page-intro">POS visits appear automatically. Open a visit to see its automation decisions, sent message, delivery status, and Review link clicked activity.</p></div><button className="button-primary" onClick={() => setManualOpen(true)}>+ Record manual visit</button></div>
    {message && <p className="mt-5 rounded-xl bg-white px-4 py-3 text-sm text-forest">{message}</p>}
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Total visits" value={visits.length}/><Metric label="Messages created" value={sent}/><Metric label="Review links clicked" value={clicked}/></div>
    <section className="mt-6 overflow-hidden rounded-xl border border-ink/8 bg-white"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-ink/8 px-5 py-4"><div><h2 className="font-semibold">Visit history</h2><p className="mt-1 text-xs text-ink/45">Source shows whether the record arrived from POS/API or was entered manually.</p></div><input className="field max-w-xs" placeholder="Search customer or location" value={search} onChange={(event) => setSearch(event.target.value)}/></header><div className="hidden grid-cols-[1.3fr_1fr_1fr_1fr_100px] gap-4 border-b border-ink/8 bg-paper/70 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-ink/35 lg:grid"><span>Customer</span><span>Location & time</span><span>Source</span><span>Message activity</span><span></span></div><div className="divide-y divide-ink/8">{filtered.map((visit) => { const deliveries = visit.dispatches.filter((item) => item.delivery); const linkClicked = deliveries.some((item) => item.delivery?.review_link?.first_clicked_at); return <article key={visit.id} className="grid gap-4 px-5 py-4 lg:grid-cols-[1.3fr_1fr_1fr_1fr_100px] lg:items-center"><div><p className="text-sm font-semibold">{visit.customer ? `${visit.customer.first_name} ${visit.customer.last_name ?? ""}` : "Unresolved customer"}</p><p className="mt-1 text-xs capitalize text-ink/45">{visit.type}</p></div><div><p className="text-xs font-medium">{visit.location.name}</p><p className="mt-1 text-[11px] text-ink/45">{new Date(visit.completed_at).toLocaleString()}</p></div><span className="pill w-fit capitalize">{visit.source.replaceAll("_", " ")}</span><div className="flex flex-wrap gap-2"><span className="pill">{deliveries.length} message(s)</span>{linkClicked && <span className="pill bg-emerald-50 text-emerald-800">Review link clicked</span>}</div><button className="rounded-lg border border-ink/10 px-3 py-2 text-xs font-semibold" onClick={() => setSelected(visit)}>Details</button></article>; })}{filtered.length === 0 && <p className="px-6 py-16 text-center text-sm text-ink/45">No visits match this search.</p>}</div></section>
    {manualOpen && <ManualDialog locations={locations} customers={customers} onClose={() => setManualOpen(false)} onSave={createVisit}/>} {selected && <VisitDialog visit={selected} onClose={() => setSelected(null)}/>} </div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-ink/8 bg-white p-5"><p className="text-xs text-ink/45">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function ManualDialog({ locations, customers, onClose, onSave }: { locations: Location[]; customers: Customer[]; onClose: () => void; onSave: (data: FormData) => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/55 p-4"><form action={onSave} className="w-full max-w-2xl rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="eyebrow">Manual entry</p><h2 className="mt-1 text-xl font-semibold">Record completed visit</h2></div><button type="button" onClick={onClose}>×</button></div><p className="mt-3 text-xs leading-5 text-ink/45">Use this only when a visit did not arrive from the connected POS. Matching active automations are evaluated after saving.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="label">Location<select className="field" name="location_id" required defaultValue=""><option value="" disabled>Select location</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="label">Customer<select className="field" name="customer_id" required defaultValue=""><option value="" disabled>Select customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.first_name} {item.last_name}</option>)}</select></label><label className="label">Completed at<input className="field" type="datetime-local" name="completed_at" required/></label><label className="label">Visit type<select className="field" name="type" defaultValue="service"><option value="service">Service</option><option value="appointment">Appointment</option><option value="purchase">Purchase</option><option value="payment">Payment</option><option value="other">Other</option></select></label><label className="label">Amount (optional)<input className="field" type="number" min="0" step="0.01" name="amount"/></label><label className="label">Currency<input className="field" name="currency" defaultValue="USD" maxLength={3}/></label><label className="label sm:col-span-2">Consent evidence (optional)<select className="field" name="consent_source"><option value="">Do not add consent</option><option value="written">Written</option><option value="verbal">Verbal</option><option value="web_form">Web form</option><option value="provider">Provider</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="rounded-lg border border-ink/10 px-4 py-2" onClick={onClose}>Cancel</button><button className="button-primary">Save visit</button></div></form></div>; }
function VisitDialog({ visit, onClose }: { visit: Visit; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/55 p-4"><section className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="eyebrow">Visit detail</p><h2 className="mt-1 text-xl font-semibold">{visit.customer?.first_name ?? "Unresolved customer"} · {visit.location.name}</h2></div><button onClick={onClose}>×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><MetricText label="Completed" value={new Date(visit.completed_at).toLocaleString()}/><MetricText label="Source" value={visit.source.replaceAll("_", " ")}/><MetricText label="Type" value={visit.type}/></div><h3 className="mt-7 font-semibold">Automation and message timeline</h3><div className="mt-3 space-y-3">{visit.dispatches.map((dispatch) => <article className="rounded-xl border border-ink/10 p-4" key={dispatch.id}><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{dispatch.rule?.name ?? "Automation"}</p><span className="pill capitalize">{dispatch.delivery?.status ?? dispatch.decision}</span></div>{dispatch.delivery ? <><p className="mt-2 text-xs text-ink/45">{dispatch.delivery.template?.name} · {dispatch.delivery.channel.toUpperCase()}</p>{dispatch.delivery.body_snapshot && <p className="mt-3 whitespace-pre-wrap rounded-lg bg-paper p-3 text-sm">{dispatch.delivery.body_snapshot}</p>}<p className="mt-3 text-xs font-semibold text-forest">{dispatch.delivery.review_link?.first_clicked_at ? `Review link clicked ${new Date(dispatch.delivery.review_link.first_clicked_at).toLocaleString()} (${dispatch.delivery.review_link.click_count} click(s))` : "Review link not clicked"}</p></> : <p className="mt-2 text-xs text-ink/45">{dispatch.decision === "scheduled" ? `Scheduled for ${new Date(dispatch.scheduled_for!).toLocaleString()}` : `Skipped: ${dispatch.reason_code ?? "not eligible"}`}</p>}</article>)}{visit.dispatches.length === 0 && <p className="text-sm text-ink/45">No automation matched this visit.</p>}</div></section></div>; }
function MetricText({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-paper p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-ink/35">{label}</p><p className="mt-2 text-sm font-semibold capitalize">{value}</p></div>; }
