"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";

type Channel = "sms" | "whatsapp";
type Consent = { channel: Channel; status: string };
type Suppression = { channel: Channel };
type Customer = { id: string; first_name: string; last_name?: string; email?: string; phone_e164?: string; status: string; source: string; consents: Consent[]; suppressions: Suppression[] };
type Meta = { current_page: number; last_page: number; total: number };
type ImportPreview = { valid_rows: number; preview: Record<string, string>[]; errors: { row: number; reason: string }[] };

export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [meta, setMeta] = useState<Meta>({ current_page: 1, last_page: 1, total: 0 });
  const [search, setSearch] = useState(""); const [dialog, setDialog] = useState<"add" | "import" | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load(page = 1) { const result = await api<{ data: Customer[]; meta: Meta }>(`/api/v1/customers?page=${page}${search ? `&search=${encodeURIComponent(search)}` : ""}`, {}, true); setCustomers(result.data); setMeta(result.meta); }
  useEffect(() => { void api<{ data: Customer[]; meta: Meta }>("/api/v1/customers", {}, true).then((result) => { setCustomers(result.data); setMeta(result.meta); }).catch((error: Error) => setMessage(error.message)); }, []);
  async function create(formData: FormData) { setBusy(true); setMessage(""); try { const result = await api<{ data: Customer }>("/api/v1/customers", { method: "POST", body: JSON.stringify({ first_name: formData.get("first_name"), last_name: formData.get("last_name") || null, phone: formData.get("phone"), email: formData.get("email") || null, source: "manual" }) }, true); if (formData.get("consent") === "granted") await api(`/api/v1/customers/${result.data.id}/consents`, { method: "POST", body: JSON.stringify({ channel: formData.get("consent_channel"), status: "granted", source: formData.get("consent_source"), disclosure_version: "manual-entry-v1" }) }, true); setDialog(null); setMessage("Customer added successfully."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add customer."); } finally { setBusy(false); } }
  async function suppress(id: string, channel: Channel) { setBusy(true); try { await api(`/api/v1/customers/${id}/suppressions`, { method: "POST", body: JSON.stringify({ channel, reason: "manual" }) }, true); await load(meta.current_page); } finally { setBusy(false); } }
  const consentState = (customer: Customer, channel: Channel) => customer.suppressions.some((item) => item.channel === channel) ? "Suppressed" : customer.consents.find((item) => item.channel === channel)?.status === "granted" ? "Consented" : "Not recorded";

  return <div className="mx-auto max-w-[1380px]"><header className="flex flex-col justify-between gap-5 border-b border-ink/8 pb-6 lg:flex-row lg:items-end"><div><p className="eyebrow">Engagement · Customers</p><h1 className="page-title">Customers</h1><p className="page-intro">Manage consent-aware contacts from manual entry, CSV imports, and connected providers.</p></div><div className="flex gap-2"><button className="rounded-lg border border-ink/10 bg-white px-4 py-2.5 text-sm font-semibold" onClick={() => setDialog("import")}>Import CSV</button><button className="button-primary" onClick={() => setDialog("add")}>+ Add customer</button></div></header>
    {message && <p role="status" className="mt-5 rounded-xl border border-forest/15 bg-white px-4 py-3 text-sm text-forest">{message}</p>}
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Total customers" value={meta.total}/><Metric label="Visible page" value={customers.length}/><Metric label="SMS consent" value={customers.filter((item) => consentState(item, "sms") === "Consented").length} detail="On this page"/></div>
    <section className="mt-6 overflow-hidden rounded-xl border border-ink/8 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-ink/8 px-5 py-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold">Customer directory</h2><p className="mt-1 text-[11px] text-ink/40">Consent and suppression are evaluated separately for each channel.</p></div><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); void load(); }}><input aria-label="Search customers" className="rounded-lg border border-ink/10 bg-paper px-3 py-2 text-xs" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, email, or phone"/><button className="rounded-lg border border-ink/10 px-3 py-2 text-xs font-semibold">Search</button></form></div>
      <div className="hidden grid-cols-[1.25fr_1.1fr_105px_110px_110px_100px] gap-4 border-b border-ink/8 bg-paper/70 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-ink/35 lg:grid"><span>Customer</span><span>Contact</span><span>SMS</span><span>WhatsApp</span><span>Source</span><span>Actions</span></div><div className="divide-y divide-ink/8">{customers.length ? customers.map((customer) => <article key={customer.id} className="grid gap-4 px-5 py-4 lg:grid-cols-[1.25fr_1.1fr_105px_110px_110px_100px] lg:items-center"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-forest/8 text-xs font-bold text-forest">{customer.first_name[0]}{customer.last_name?.[0] ?? ""}</span><div><p className="text-sm font-semibold">{customer.first_name} {customer.last_name}</p><p className="mt-0.5 text-[10px] capitalize text-ink/40">{customer.status}</p></div></div><div><p className="text-xs">{customer.phone_e164}</p><p className="mt-1 truncate text-[11px] text-ink/40">{customer.email || "No email"}</p></div><ConsentPill value={consentState(customer, "sms")}/><ConsentPill value={consentState(customer, "whatsapp")}/><span className="text-xs capitalize text-ink/55">{customer.source}</span><div>{consentState(customer, "sms") !== "Suppressed" && <button disabled={busy} className="text-[11px] font-semibold text-red-700 underline" onClick={() => suppress(customer.id, "sms")}>Suppress SMS</button>}</div></article>) : <div className="px-6 py-16 text-center"><p className="text-sm font-semibold">No customers found</p><p className="mt-2 text-xs text-ink/45">Add a customer or import a consent-aware CSV file.</p></div>}</div>
      <footer className="flex items-center justify-between border-t border-ink/8 px-5 py-4 text-xs text-ink/45"><span>Page {meta.current_page} of {meta.last_page} · {meta.total} customers</span><div className="flex gap-2"><button className="rounded-lg border border-ink/10 px-3 py-2 disabled:opacity-40" disabled={meta.current_page <= 1} onClick={() => load(meta.current_page - 1)}>Previous</button><button className="rounded-lg border border-ink/10 px-3 py-2 disabled:opacity-40" disabled={meta.current_page >= meta.last_page} onClick={() => load(meta.current_page + 1)}>Next</button></div></footer></section>
    {dialog === "add" && <AddCustomerDialog busy={busy} onClose={() => setDialog(null)} onSave={create}/>} {dialog === "import" && <ImportDialog onClose={() => setDialog(null)} onComplete={async (text) => { setDialog(null); setMessage(text); await load(); }}/>} 
  </div>;
}

function AddCustomerDialog({ busy, onClose, onSave }: { busy: boolean; onClose: () => void; onSave: (data: FormData) => void }) { return <Modal title="Add customer" eyebrow="Customer record" onClose={onClose}><form action={onSave} className="space-y-5 p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" required><input className="field" name="first_name" required autoFocus/></Field><Field label="Last name"><input className="field" name="last_name"/></Field><Field label="Mobile phone" required hint="International E.164 format"><input className="field" name="phone" type="tel" required pattern="\+[1-9][0-9]{7,14}" placeholder="+12025550123"/></Field><Field label="Email"><input className="field" name="email" type="email"/></Field></div><div className="rounded-xl border border-ink/8 bg-paper p-4"><p className="text-xs font-semibold">Messaging consent</p><p className="mt-1 text-[11px] leading-5 text-ink/45">Contact information alone never implies consent. Record it only when you have evidence.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Status"><select className="field" name="consent" defaultValue="none"><option value="none">Not recorded</option><option value="granted">Granted</option></select></Field><Field label="Channel"><select className="field" name="consent_channel"><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></Field><Field label="Evidence source"><select className="field" name="consent_source"><option value="written">Written</option><option value="verbal">Verbal</option><option value="web_form">Web form</option><option value="provider">Provider</option></select></Field></div></div><footer className="flex justify-end gap-2"><button type="button" className="rounded-lg border border-ink/10 px-4 py-2.5 text-sm font-semibold" onClick={onClose}>Cancel</button><button className="button-primary" disabled={busy}>{busy ? "Saving…" : "Add customer"}</button></footer></form></Modal>; }

function ImportDialog({ onClose, onComplete }: { onClose: () => void; onComplete: (message: string) => void }) {
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<ImportPreview | null>(null); const [progress, setProgress] = useState(0); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  function downloadSample() { const csv = "first_name,last_name,email,phone\nAva,Morgan,ava@example.com,+12025550123\n"; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "revieworbit-customer-import-template.csv"; anchor.click(); URL.revokeObjectURL(url); }
  async function inspect() { if (!file) return; setError(""); setStatus("Uploading and validating rows…"); setProgress(25); const data = new FormData(); data.set("file", file); data.set("preview", "1"); try { const result = await api<{ data: ImportPreview }>("/api/v1/customers/import-csv", { method: "POST", body: data }, true); setPreview(result.data); setProgress(60); setStatus(`${result.data.valid_rows} valid rows ready to import.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to validate the CSV."); setProgress(0); } }
  async function commit() { if (!file) return; setError(""); setProgress(75); setStatus("Creating customer records…"); const data = new FormData(); data.set("file", file); data.set("preview", "0"); try { const result = await api<{ data: { created: number; skipped: number } }>("/api/v1/customers/import-csv", { method: "POST", body: data }, true); setProgress(100); onComplete(`Import complete: ${result.data.created} created, ${result.data.skipped} skipped.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to import the CSV."); } }
  return <Modal title="Import customers" eyebrow="CSV import" onClose={onClose}><div className="space-y-5 p-6"><div className="rounded-xl border border-forest/15 bg-mint/30 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold">Start with the ReviewOrbit template</p><p className="mt-1 text-[11px] text-ink/45">Required headers: first_name and phone. Optional: last_name and email.</p></div><button className="rounded-lg border border-forest/20 bg-white px-3 py-2 text-xs font-semibold text-forest" onClick={downloadSample}>Download sample CSV</button></div></div><label className="grid cursor-pointer place-items-center rounded-xl border-2 border-dashed border-ink/12 bg-paper px-6 py-10 text-center"><input className="sr-only" type="file" accept=".csv,text/csv" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setProgress(0); }}/><span className="text-sm font-semibold">{file?.name ?? "Choose a CSV file"}</span><span className="mt-2 text-xs text-ink/40">Maximum 500 rows and 2 MB</span></label>{progress > 0 && <div><div className="flex justify-between text-xs"><span>{status}</span><strong>{progress}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink/8"><div className="h-full rounded-full bg-forest transition-all" style={{ width: `${progress}%` }}/></div></div>}{error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-xs text-red-800">{error}</p>}{preview && <div className="rounded-xl border border-ink/8"><div className="flex justify-between border-b border-ink/8 px-4 py-3 text-xs"><strong>Validation result</strong><span>{preview.valid_rows} valid · {preview.errors.length} issues</span></div>{preview.errors.length > 0 && <div className="max-h-28 overflow-auto px-4 py-3 text-[11px] text-red-700">{preview.errors.slice(0, 8).map((item) => <p key={`${item.row}-${item.reason}`}>Row {item.row}: {item.reason}</p>)}</div>}</div>}<footer className="flex justify-end gap-2"><button className="rounded-lg border border-ink/10 px-4 py-2.5 text-sm font-semibold" onClick={onClose}>Cancel</button>{!preview ? <button className="button-primary" disabled={!file} onClick={inspect}>Validate file</button> : <button className="button-primary" disabled={preview.valid_rows === 0} onClick={commit}>Import {preview.valid_rows} customers</button>}</footer></div></Modal>;
}
function Modal({ title, eyebrow, onClose, children }: { title: string; eyebrow: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/55 p-4"><section role="dialog" aria-modal="true" aria-labelledby="customer-dialog-title" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-ink/8 px-6 py-5"><div><p className="eyebrow">{eyebrow}</p><h2 id="customer-dialog-title" className="mt-1 text-xl font-semibold">{title}</h2></div><button aria-label="Close dialog" className="rounded-lg border border-ink/10 px-2.5 py-1.5" onClick={onClose}>×</button></header>{children}</section></div>; }
function Metric({ label, value, detail }: { label: string; value: number; detail?: string }) { return <div className="rounded-xl border border-ink/8 bg-white p-4 shadow-sm"><p className="text-xs text-ink/45">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-ink/35">{detail ?? "Workspace records"}</p></div>; }
function ConsentPill({ value }: { value: string }) { return <span className={`pill w-fit ${value === "Consented" ? "bg-emerald-50 text-emerald-800" : value === "Suppressed" ? "bg-red-50 text-red-800" : ""}`}>{value}</span>; }
function Field({ label, hint, required, children }: { label: string; hint?: string; required?: boolean; children: React.ReactNode }) { return <label className="label"><span>{label}{required && <span className="ml-1 text-red-600">*</span>}</span>{children}{hint && <span className="mt-1 block text-[10px] font-normal text-ink/40">{hint}</span>}</label>; }
