import { notFound } from "next/navigation";
import { ModuleScreen, type ModuleDefinition } from "@/components/module-screen";

const definitions: Record<string, ModuleDefinition> = {
  setup: { eyebrow: "Workspace", title: "Setup checklist", description: "Review onboarding readiness and return to the guided setup whenever business configuration changes.", status: "available", primaryAction: "Open guided setup", primaryHref: "/onboarding", metrics: [{ label: "Business profile", value: "Ready", detail: "Identity and timezone" }, { label: "Location", value: "Ready", detail: "Review destination configured" }, { label: "Consent policy", value: "Confirmed", detail: "Responsibility acknowledged" }, { label: "Visit source", value: "Manual", detail: "POS can be connected later" }], capabilities: [{ name: "Guided onboarding", description: "Business, location, message, consent, and integration steps.", state: "Available" }, { name: "Server-derived readiness", description: "The API validates required configuration before completion.", state: "Available" }, { name: "Concierge support", description: "Platform administrators can assist through audited access.", state: "Available" }] },
  messages: { eyebrow: "Customer engagement", title: "Messages", description: "Monitor outbound requests, delivery status, replies, opt-outs, and follow-up activity.", status: "planned", primaryAction: "Compose test message", metrics: [{ label: "Sent today", value: "—", detail: "Messaging starts in Milestone 7" }, { label: "Delivery rate", value: "—", detail: "Provider callbacks required" }, { label: "Replies", value: "—", detail: "Inbound handling planned" }, { label: "Opt-outs", value: "—", detail: "Suppression remains enforced" }], capabilities: [{ name: "Message timeline", description: "Per-customer outbound and provider-event history.", state: "Planned" }, { name: "Delivery callbacks", description: "Queued provider status reconciliation and failure reasons.", state: "Planned" }, { name: "Inbound replies and opt-outs", description: "STOP handling and immediate suppression updates.", state: "Planned" }] },
  "review-links": { eyebrow: "Customer engagement", title: "Review links", description: "Manage secure review destinations and measure Review link clicked events without claiming submitted reviews.", status: "planned", primaryAction: "Create tracking link", metrics: [{ label: "Active links", value: "—", detail: "Tracking starts in Milestone 7" }, { label: "Link clicks", value: "—", detail: "Opaque token events" }, { label: "Unique customers", value: "—", detail: "No PII in tokens" }, { label: "Expired links", value: "—", detail: "Retention policy pending" }], capabilities: [{ name: "Opaque link generation", description: "High-entropy tokens with no customer or tenant identifiers.", state: "Planned" }, { name: "Verified redirect", description: "Server-owned destination lookup and click recording.", state: "Planned" }, { name: "Click attribution", description: "Uses the compliant Review link clicked label only.", state: "Planned" }] },
  webhooks: { eyebrow: "Connections", title: "Webhook activity", description: "Inspect provider events, signature results, processing state, and idempotent reprocessing.", status: "partial", metrics: [{ label: "Received today", value: "0", detail: "Generic endpoint is available" }, { label: "Processed", value: "0", detail: "No recent events" }, { label: "Failed", value: "0", detail: "No unresolved failures" }, { label: "Duplicates", value: "0", detail: "Idempotency is enforced" }], capabilities: [{ name: "Generic signed webhook", description: "HMAC verification and replay tolerance are implemented.", state: "Available" }, { name: "Event viewer", description: "Searchable payload-minimized operational history.", state: "Planned" }, { name: "Manual reprocessing", description: "Permission-checked retry through the original code path.", state: "Planned" }] },
  analytics: { eyebrow: "Reports", title: "Analytics", description: "Understand delivery, Review link clicked, follow-up, opt-out, and skipped-automation performance.", status: "planned", primaryAction: "Export report", metrics: [{ label: "Messages sent", value: "—", detail: "Awaiting messaging" }, { label: "Delivery rate", value: "—", detail: "Awaiting callbacks" }, { label: "Link click rate", value: "—", detail: "Awaiting tracking" }, { label: "Skipped automations", value: "—", detail: "Decision records available" }], capabilities: [{ name: "Performance overview", description: "Date, location, automation, and template filters.", state: "Planned" }, { name: "Skip-reason analysis", description: "Consent, suppression, duplicate, quiet-hour, and frequency outcomes.", state: "Planned" }, { name: "CSV export", description: "Tenant-scoped aggregate exports without unnecessary PII.", state: "Planned" }] },
  activity: { eyebrow: "Reports", title: "Activity & audit", description: "Review business configuration changes and sensitive customer-data actions in one timeline.", status: "partial", metrics: [{ label: "Events today", value: "—", detail: "Audit records are persisted" }, { label: "Team actions", value: "—", detail: "Interface pending" }, { label: "Support sessions", value: "—", detail: "Admin access is audited" }, { label: "Exports", value: "0", detail: "No exports recorded" }], capabilities: [{ name: "Immutable audit records", description: "Actor, business, target, request ID, and changed fields are stored.", state: "Available" }, { name: "Search and filters", description: "Filter by actor, action, resource, and time range.", state: "Planned" }, { name: "Audit export", description: "Permission-protected operational export.", state: "Planned" }] },
  team: { eyebrow: "Account", title: "Team & roles", description: "Invite managers and viewers, review pending invitations, and enforce least-privilege access.", status: "partial", primaryAction: "Invite team member", metrics: [{ label: "Active members", value: "1", detail: "Current owner included" }, { label: "Pending invites", value: "0", detail: "No pending invitations" }, { label: "Managers", value: "0", detail: "Can configure operations" }, { label: "Viewers", value: "0", detail: "Read-only access" }], capabilities: [{ name: "Role enforcement", description: "Owner, manager, and viewer API permissions are active.", state: "Available" }, { name: "Invitation API", description: "Secure expiring invitation tokens are implemented.", state: "Available" }, { name: "Team management UI", description: "Invitation and membership controls are next.", state: "Planned" }] },
  billing: { eyebrow: "Account", title: "Plan & billing", description: "Review subscription, usage allowances, invoices, and payment details.", status: "planned", primaryAction: "Manage subscription", metrics: [{ label: "Current plan", value: "Trial", detail: "Billing provider not connected" }, { label: "Billing cycle", value: "—", detail: "No active subscription" }, { label: "Messages used", value: "0", detail: "Messaging not active" }, { label: "Next invoice", value: "—", detail: "No invoice scheduled" }], capabilities: [{ name: "Subscription plans", description: "Plan catalogue and feature entitlements.", state: "Planned" }, { name: "Usage metering", description: "Message and media generation allowances.", state: "Planned" }, { name: "Invoices and payment method", description: "Secure billing-provider hosted workflow.", state: "Planned" }] },
  help: { eyebrow: "Account", title: "Help & support", description: "Find setup guidance, integration references, and secure ways to request platform assistance.", status: "partial", primaryAction: "Contact support", metrics: [{ label: "Setup guides", value: "6", detail: "Product documentation" }, { label: "API guides", value: "2", detail: "Generic API and webhooks" }, { label: "Open requests", value: "0", detail: "No support requests" }, { label: "System status", value: "Healthy", detail: "Local environment" }], capabilities: [{ name: "Product documentation", description: "Architecture, security, API, deployment, and integration guides.", state: "Available" }, { name: "Support requests", description: "Audited customer-to-platform assistance workflow.", state: "Planned" }, { name: "In-app guidance", description: "Contextual help attached to each module.", state: "Planned" }] },
};

export default async function CustomerModulePage({ params }: { params: Promise<{ module: string }> }) {
  const { module } = await params;
  const definition = definitions[module];
  if (!definition) notFound();
  return <ModuleScreen module={definition}/>;
}
