"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";

type Activity = { id: string; click_count: number; first_clicked_at?: string; last_clicked_at?: string; created_at: string; expires_at: string; customer: { first_name: string; last_name?: string }; location: { name: string }; destination?: { provider: string }; visit: { completed_at: string; source: string }; deliveries: { id: string; status: string; channel: string; body_snapshot?: string; template?: { name: string } }[] };
type Meta = { total: number; messages_sent: number; links_clicked: number; click_rate: number };

export default function ReviewLinksPage() {
  const [activities, setActivities] = useState<Activity[]>([]); const [meta, setMeta] = useState<Meta>({ total: 0, messages_sent: 0, links_clicked: 0, click_rate: 0 }); const [resend, setResend] = useState<Activity | null>(null); const [message, setMessage] = useState("");
  async function load() { const result = await api<{ data: Activity[]; meta: Meta }>("/api/v1/review-links", {}, true); setActivities(result.data); setMeta(result.meta); }
  useEffect(() => { void api<{ data: Activity[]; meta: Meta }>("/api/v1/review-links", {}, true).then((result) => { setActivities(result.data); setMeta(result.meta); }).catch((error: Error) => setMessage(error.message)); }, []);
  async function send(data: FormData) { if (!resend) return; try { await api(`/api/v1/review-links/${resend.id}/resend`, { method: "POST", body: JSON.stringify({ body: data.get("body") }) }, true); setResend(null); setMessage("Custom follow-up queued. Consent, suppression, credits, and the destination were revalidated."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to resend message."); } }
  return <div className="mx-auto max-w-7xl"><p className="eyebrow">Engagement tracking</p><h1 className="page-title">Review links</h1><p className="page-intro">Measure Review link clicked events and message delivery without claiming that a review was submitted. Every redirect uses an opaque, expiring link.</p>{message && <p className="mt-5 rounded-xl bg-white px-4 py-3 text-sm text-forest">{message}</p>}
    <div className="mt-7 grid gap-4 sm:grid-cols-4"><Card label="Messages sent" value={meta.messages_sent}/><Card label="Tracking links" value={meta.total}/><Card label="Links clicked" value={meta.links_clicked}/><Card label="Click rate" value={`${meta.click_rate}%`}/></div>
    <section className="mt-6 overflow-hidden rounded-xl border border-ink/8 bg-white"><header className="border-b border-ink/8 px-5 py-4"><h2 className="font-semibold">Customer message activity</h2><p className="mt-1 text-xs text-ink/45">Open activity by customer, location, destination, delivery, and click status.</p></header><div className="hidden grid-cols-[1.2fr_1fr_1fr_1fr_110px] gap-4 border-b border-ink/8 bg-paper/70 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-ink/35 lg:grid"><span>Customer</span><span>Location & destination</span><span>Message</span><span>Link activity</span><span></span></div><div className="divide-y divide-ink/8">{activities.map((item) => { const delivery = item.deliveries[0]; return <article key={item.id} className="grid gap-4 px-5 py-4 lg:grid-cols-[1.2fr_1fr_1fr_1fr_110px] lg:items-center"><div><p className="text-sm font-semibold">{item.customer.first_name} {item.customer.last_name}</p><p className="mt-1 text-[11px] text-ink/45">Visit {new Date(item.visit.completed_at).toLocaleDateString()} · {item.visit.source}</p></div><div><p className="text-xs font-medium">{item.location.name}</p><p className="mt-1 text-[11px] capitalize text-ink/45">{item.destination?.provider ?? "Saved destination"}</p></div><div><p className="text-xs font-medium">{delivery?.template?.name ?? "Custom follow-up"}</p><p className="mt-1 text-[11px] uppercase text-ink/45">{delivery?.channel ?? "—"} · {delivery?.status ?? "link created"}</p></div><div>{item.first_clicked_at ? <><span className="pill bg-emerald-50 text-emerald-800">Review link clicked</span><p className="mt-1 text-[11px] text-ink/45">{item.click_count} click(s) · {new Date(item.last_clicked_at!).toLocaleString()}</p></> : <span className="pill">Not clicked</span>}</div><button className="rounded-lg border border-forest/20 px-3 py-2 text-xs font-semibold text-forest" onClick={() => setResend(item)}>Resend</button></article>; })}{activities.length === 0 && <div className="px-6 py-16 text-center"><p className="text-sm font-semibold">No tracking links yet</p><p className="mt-2 text-xs text-ink/45">Links are created automatically when an eligible message is sent.</p></div>}</div></section>
    {resend && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/55 p-4"><form action={send} className="w-full max-w-xl rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="eyebrow">Controlled resend</p><h2 className="mt-1 text-xl font-semibold">Message {resend.customer.first_name}</h2></div><button type="button" onClick={() => setResend(null)}>×</button></div><p className="mt-3 text-xs leading-5 text-ink/45">A fresh tracking link is appended automatically. Sending is blocked if consent, suppression, channel configuration, or plan credits are no longer valid.</p><label className="label mt-5">Custom message<textarea name="body" required minLength={10} maxLength={1500} className="field min-h-40" defaultValue={`Hi {{customer_first_name}}, thank you for visiting {{business_name}}. If you have a moment, we would appreciate your honest feedback: {{review_link}}`}/></label><div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded-lg border border-ink/10 px-4 py-2" onClick={() => setResend(null)}>Cancel</button><button className="button-primary">Send follow-up</button></div></form></div>}
  </div>;
}
function Card({ label, value }: { label: string; value: number | string }) { return <div className="rounded-xl border border-ink/8 bg-white p-5"><p className="text-xs text-ink/45">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
