"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { PasswordInput } from "@/components/password-input";
import { UsPhoneInput } from "@/components/us-phone-input";

type Profile = { id:string; name:string; email:string; phone:string|null; has_avatar:boolean; avatar_url:string|null };

export default function ProfileSettingsPage() {
  const [profile,setProfile]=useState<Profile|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{void api<{data:Profile}>("/api/v1/profile",{},true).then(({data})=>setProfile(data)).catch((error:Error)=>setMessage(error.message));},[]);
  async function saveProfile(data:FormData){setBusy(true);setMessage("");try{const result=await api<{data:Profile}>("/api/v1/profile",{method:"PATCH",body:JSON.stringify({name:data.get("name"),email:data.get("email"),phone:data.get("phone")||null})},true);setProfile(result.data);setMessage("Profile saved.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to save profile.");}finally{setBusy(false);}}
  async function uploadAvatar(data:FormData){setBusy(true);setMessage("");try{const result=await api<{data:Profile}>("/api/v1/profile/avatar",{method:"POST",body:data},true);setProfile({...result.data,avatar_url:`${result.data.avatar_url}?v=${Date.now()}`});setMessage("Profile photo updated.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to upload photo.");}finally{setBusy(false);}}
  async function changePassword(data:FormData){setBusy(true);setMessage("");try{const result=await api<{message:string}>("/api/v1/profile/password",{method:"PUT",body:JSON.stringify({current_password:data.get("current_password"),password:data.get("password"),password_confirmation:data.get("password_confirmation")})},true);setMessage(result.message);(document.getElementById("password-form") as HTMLFormElement)?.reset();}catch(error){setMessage(error instanceof Error?error.message:"Unable to change password.");}finally{setBusy(false);}}
  if(!profile)return <div className="mx-auto max-w-5xl"><p className="eyebrow">Account</p><h1 className="page-title">Loading profile…</h1>{message&&<Notice text={message}/>}</div>;
  return <div className="mx-auto max-w-5xl"><p className="eyebrow">Account</p><h1 className="page-title">Profile settings</h1><p className="page-intro">Manage your personal contact details, profile photo, and password.</p>{message&&<Notice text={message}/>}<div className="mt-7 grid gap-6 lg:grid-cols-[.75fr_1.25fr]">
    <section className="rounded-2xl border border-ink/8 bg-white p-6"><h2 className="text-xl font-semibold">Profile photo</h2><div className="mt-5 grid size-28 place-items-center overflow-hidden rounded-2xl bg-forest text-3xl font-bold text-white">{profile.avatar_url?<img className="size-full object-cover" src={profile.avatar_url} alt="Profile"/>:profile.name.split(" ").map(value=>value[0]).join("").slice(0,2)}</div><p className="mt-4 text-sm leading-6 text-ink/50">JPG, PNG, or WebP. Use a square photo between 128px and 4,000px, up to 5 MB.</p><form action={uploadAvatar} className="mt-4"><input className="block w-full text-sm" name="avatar" type="file" accept="image/jpeg,image/png,image/webp" required/><button className="button-primary mt-4" disabled={busy}>Upload photo</button></form></section>
    <section className="rounded-2xl border border-ink/8 bg-white p-6"><h2 className="text-xl font-semibold">Personal details</h2><form action={saveProfile} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="label">Full name<input className="field" name="name" defaultValue={profile.name} required/></label><label className="label">Email address<input className="field" name="email" type="email" defaultValue={profile.email} required/></label><label className="label sm:col-span-2">Phone number <span className="font-normal text-ink/40">(optional)</span><UsPhoneInput name="phone" defaultValue={profile.phone}/></label><div className="sm:col-span-2"><button className="button-primary" disabled={busy}>Save profile</button></div></form></section>
  </div><section className="mt-6 rounded-2xl border border-ink/8 bg-white p-6"><p className="eyebrow">Security</p><h2 className="mt-1 text-xl font-semibold">Change password</h2><p className="mt-2 text-sm text-ink/50">Changing your password signs out your other browser and mobile sessions.</p><form id="password-form" action={changePassword} className="mt-5 grid gap-4 md:grid-cols-3"><label className="label">Current password<PasswordInput name="current_password" autoComplete="current-password" required/></label><label className="label">New password<PasswordInput name="password" autoComplete="new-password" minLength={12} required/></label><label className="label">Confirm new password<PasswordInput name="password_confirmation" autoComplete="new-password" minLength={12} required/></label><div className="md:col-span-3"><p className="mb-3 text-xs text-ink/45">At least 12 characters with uppercase, lowercase, a number, and a symbol.</p><button className="button-primary" disabled={busy}>Change password</button></div></form></section></div>;
}
function Notice({text}:{text:string}){return <p role="status" className="mt-5 rounded-xl border border-ink/8 bg-white px-4 py-3 text-sm">{text}</p>}
