"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";

type Location = { id: string; name: string };
type Customer = { id: string; first_name: string; last_name?: string };
type Template = { id: string; name: string; status: string };
type Rule = { id: string; name: string; status: string; delay_minutes: number; frequency_limit_days: number; location?: Location };
type Visit = { id: string; type: string; completed_at: string; customer?: Customer; location: Location; dispatches: { id: string; decision: string; reason_code?: string; scheduled_for?: string }[] };
type Business = { locations: Location[] };
type IntegrationKey = { api_key: string; hmac_secret: string; key_prefix: string };

export default function AutomationsPage() {
  const [locations, setLocations] = useState<Location[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [visits, setVisits] = useState<Visit[]>([]); const [message, setMessage] = useState(""); const [newKey, setNewKey] = useState<IntegrationKey | null>(null);
  async function load() { const [business, customerResult, templateResult, ruleResult, visitResult] = await Promise.all([api<{ data: Business }>("/api/v1/business", {}, true), api<{ data: Customer[] }>("/api/v1/customers", {}, true), api<{ data: Template[] }>("/api/v1/templates", {}, true), api<{ data: Rule[] }>("/api/v1/automations", {}, true), api<{ data: Visit[] }>("/api/v1/visits", {}, true)]); setLocations(business.data.locations); setCustomers(customerResult.data); setTemplates(templateResult.data); setRules(ruleResult.data); setVisits(visitResult.data); }
  useEffect(() => { void Promise.all([api<{ data: Business }>("/api/v1/business", {}, true), api<{ data: Customer[] }>("/api/v1/customers", {}, true), api<{ data: Template[] }>("/api/v1/templates", {}, true), api<{ data: Rule[] }>("/api/v1/automations", {}, true), api<{ data: Visit[] }>("/api/v1/visits", {}, true)]).then(([business, customerResult, templateResult, ruleResult, visitResult]) => { setLocations(business.data.locations); setCustomers(customerResult.data); setTemplates(templateResult.data); setRules(ruleResult.data); setVisits(visitResult.data); }).catch((error: Error) => setMessage(error.message)); }, []);
  async function createRule(formData: FormData) { try { await api("/api/v1/automations", { method: "POST", body: JSON.stringify({ name: formData.get("name"), location_id: formData.get("location_id") || null, message_template_id: formData.get("message_template_id"), delay_minutes: Number(formData.get("delay_minutes")), quiet_hours_start: formData.get("quiet_hours_start"), quiet_hours_end: formData.get("quiet_hours_end"), frequency_limit_days: Number(formData.get("frequency_limit_days")), status: "active" }) }, true); setMessage("Automation activated."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create automation."); } }
  async function createVisit(formData: FormData) { try { await api("/api/v1/visits", { method: "POST", body: JSON.stringify({ location_id: formData.get("location_id"), customer_id: formData.get("customer_id"), automation_rule_id: formData.get("automation_rule_id") || null, completed_at: new Date(String(formData.get("completed_at"))).toISOString(), type: formData.get("type"), amount: formData.get("amount") || null, currency: "USD", consent_source: formData.get("consent_source") || null }) }, true); setMessage("Completed visit recorded and automation evaluated."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create visit."); } }
  async function createKey(formData: FormData) { try { const result = await api<{ data: IntegrationKey }>("/api/v1/integration-keys", { method: "POST", body: JSON.stringify({ name: formData.get("name") }) }, true); setNewKey(result.data); setMessage("Integration credentials created. Copy them now; they will not be shown again."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create API key."); } }
  return <div className="mx-auto max-w-7xl"><p className="eyebrow">Visits & automations</p><h1 className="page-title">Turn eligible visits into scheduled decisions</h1><p className="page-intro">This milestone evaluates consent, suppression, duplicates, frequency, and location quiet hours. It records schedules only; Milestone 7 will send messages.</p>{message && <p role="status" className="mt-6 rounded-xl bg-white px-4 py-3 text-sm text-forest">{message}</p>}
    <div className="mt-8 grid gap-6 xl:grid-cols-3"><form action={createRule} className="panel space-y-4"><h2 className="text-xl font-semibold">New automation</h2><label className="label">Name<input className="field" name="name" required placeholder="Completed visit follow-up" /></label><label className="label">Location<select className="field" name="location_id"><option value="">All locations</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="label">Message template<select className="field" name="message_template_id" required defaultValue=""><option value="" disabled>Select template</option>{templates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="label">Delay minutes<input className="field" name="delay_minutes" type="number" min="0" defaultValue="60" /></label><label className="label">Frequency days<input className="field" name="frequency_limit_days" type="number" min="0" defaultValue="30" /></label><label className="label">Quiet start<input className="field" name="quiet_hours_start" type="time" defaultValue="20:00" /></label><label className="label">Quiet end<input className="field" name="quiet_hours_end" type="time" defaultValue="09:00" /></label></div><button className="button-primary">Activate automation</button></form>
      <form action={createVisit} className="panel space-y-4"><h2 className="text-xl font-semibold">Record completed visit</h2><label className="label">Location<select className="field" name="location_id" required defaultValue=""><option value="" disabled>Select location</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="label">Customer<select className="field" name="customer_id" required defaultValue=""><option value="" disabled>Select customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.first_name} {item.last_name}</option>)}</select></label><label className="label">Automation<select className="field" name="automation_rule_id"><option value="">All matching active rules</option>{rules.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="label">Completed at<input className="field" name="completed_at" type="datetime-local" required /></label><label className="label">Visit type<select className="field" name="type" defaultValue="service"><option value="service">Service</option><option value="purchase">Purchase</option><option value="appointment">Appointment</option><option value="payment">Payment</option></select></label></div><label className="label">Amount (optional)<input className="field" name="amount" type="number" min="0" step="0.01" /></label><label className="label">Record consent source (optional)<select className="field" name="consent_source"><option value="">Do not add consent</option><option value="written">Written</option><option value="verbal">Verbal</option><option value="web_form">Web form</option></select></label><button className="button-primary">Complete visit & evaluate</button></form>
      <form action={createKey} className="panel space-y-4"><h2 className="text-xl font-semibold">Generic integration</h2><p className="text-sm leading-6 text-ink/55">Create a bearer key and HMAC secret for normalized <code>visit.completed</code> events. Credentials are displayed once.</p><label className="label">Key name<input className="field" name="name" required placeholder="Website POS" /></label><button className="button-primary">Create credentials</button>{newKey && <div className="space-y-3 rounded-2xl bg-ink p-4 text-xs text-white"><p className="font-bold text-mint">Copy now</p><div><span className="text-white/50">API key</span><code className="mt-1 block break-all">{newKey.api_key}</code></div><div><span className="text-white/50">HMAC key prefix</span><code className="mt-1 block break-all">{newKey.key_prefix}</code></div><div><span className="text-white/50">HMAC secret</span><code className="mt-1 block break-all">{newKey.hmac_secret}</code></div></div>}</form></div>
    <section className="panel mt-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent visits and decisions</h2><span className="pill">{visits.length} visits</span></div><div className="mt-5 space-y-3">{visits.length ? visits.map((visit) => <article key={visit.id} className="rounded-2xl border border-ink/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{visit.customer?.first_name ?? "Unresolved customer"} · {visit.location.name}</p><p className="mt-1 text-sm text-ink/50">{visit.type} · {new Date(visit.completed_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{visit.dispatches.length ? visit.dispatches.map((dispatch) => <span className={`pill ${dispatch.decision === "scheduled" ? "bg-mint" : "bg-amber-50"}`} key={dispatch.id}>{dispatch.decision === "scheduled" ? `Scheduled ${new Date(dispatch.scheduled_for!).toLocaleString()}` : `Skipped: ${dispatch.reason_code}`}</span>) : <span className="pill">No matching rule</span>}</div></div></article>) : <p className="text-sm text-ink/55">No completed visits yet.</p>}</div></section>
  </div>;
}
